runtime: python27
version: 1
api_version: 1
application: babystats-root
threadsafe: true

handlers:
- url: /
  static_files: static/babystats.html
  upload: static/babystats.html
  secure: always
  login: required
  http_headers:
    X-Content-Type-Options: nosniff

- url: /baby/.*
  static_files: static/babystats.html
  upload: static/babystats.html
  secure: always
  login: required
  http_headers:
    X-Content-Type-Options: nosniff

- url: /static
  static_dir: static
  secure: always
  login: required
  http_headers:
    X-Content-Type-Options: nosniff

includes:
- cosmopolite

inbound_services:
- channel_presence
